// config.bin - 17:15:17 07/25/14, generated in 0.02 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define LockNo		0
#define LockCadet		1
#define LockYes		2

#define ReadAndWrite		0
#define ReadAndCreate		1
#define ReadOnly		2
#define ReadOnlyVerified		3

#define VSoft		0
#define VArmor		1
#define VAir		2

#define true	1
#define false	0

class CfgPatches {
	class mdh_topDownAttack {
		units[] = {};
		weapons[] = {};
		requiredAddons[] = {};
		requiredVersion = 0.1;
		author[] = {"Moerderhoschi"};
	};
};

class CfgSounds {
	class mdh_topDownAttack_locking {
		name = "mdh_topDownAttack_locking_sound";
		sound[] = {"trixie_launchers\mdh_topDownAttack\sounds\locking.ogg", 1, 1};
		titles[] = {};
	};
	
	class mdh_topDownAttack_locked {
		name = "mdh_topDownAttack_locked_sound";
		sound[] = {"trixie_launchers\mdh_topDownAttack\sounds\locked.ogg", 1, 1};
		titles[] = {};
	};
};

class CfgFunctions {
	class mdh {
		class mdh_functions {
			class mdh_topDownAttack {
				file = "trixie_launchers\mdh_topDownAttack\init.sqf";
				postInit = 1;
			};
		};
	};
};

class cfgWeapons {
	class Default {};
	
	class LauncherCore : Default {};
	
	class Launcher : LauncherCore {};
	
	class Launcher_Base_F : Launcher {};
	
	class Trixie_Javelin : Launcher_Base_F {};
	
	class launch_Titan_short_base : Trixie_Javelin {
		canLock = LockNo;
	};
};

class mdh_topDownAttack_rsc_base {
	idd = -1;
	movingEnable = "false";
	duration = 1e+010;
	fadein = 0;
	name = "mdh_topDownAttack_rsc";
};

class RscText {};

class mdh_topDownAttack_basetext : RscText {
	access = ReadAndWrite;
	type = VSoft;
	idc = -1;
	colorBackground[] = {0, 0, 0, 0};
	colorText[] = {1, 1, 1, 1};
	text = "";
	fixedWidth = 0;
	x = 0;
	y = 0;
	w = "SafeZoneW * 0.2";
	h = "SafeZoneH * 0.1";
	style = 0;
	shadow = true;
	colorShadow[] = {0, 0, 0, 0.5};
	font = "PuristaMedium";
	SizeEx = 0.04;
	linespacing = 1;
};

class mdh_topDownAttack_basepic : RscText {
	access = ReadAndWrite;
	type = VSoft;
	idc = -1;
	colorBackground[] = {0, 0, 0, 0};
	colorText[] = {0.2941, 0.2941, 0.2941, 1.0};
	text = "";
	fixedWidth = 0;
	x = "SafeZoneX + SafeZoneW * (switch (format ['%1',(getResolution select 4)]) do {case '1.77778': {0.795}; case '1.33333': {0.892}; case '1.25': {0.918}; case '2.37037': {0.721}; case '4': {0.891}; case '5.33333': {0.795}; default {0.827}})";
	y = "SafeZoneY + SafeZoneH * 0.208";
	w = "0.1045752* (((SafezoneW*3)/4)/SafezoneW)/(1/SafezoneH)";
	h = "SafezoneH*0.1045752";
	style = 48;
	shadow = true;
	colorShadow[] = {0, 0, 0, 0.5};
	font = "PuristaMedium";
	SizeEx = 0.04;
	linespacing = 1;
};

class RscTitles {
	class mdh_topDownAttack_rsc_range : mdh_topDownAttack_rsc_base {
		idd = -1;
		name = "mdh_topDownAttack_rsc_range";
		onLoad = "_this call fnc_mdh_topDownAttack_range";
		
		class controls {
			class range : mdh_topDownAttack_basetext {
				idc = -1;
				text = "";
				sizeEx = 0.08;
				x = "SafeZoneX + SafeZoneW * 0.425";
				y = "SafeZoneY + SafeZoneH * 0.7";
			};
		};
	};
	
	class mdh_topDownAttack_rsc_targetType : mdh_topDownAttack_rsc_base {
		idd = -1;
		name = "mdh_topDownAttack_rsc_targetType";
		onLoad = "_this call fnc_mdh_topDownAttack_targetType";
		
		class controls {
			class targetType : mdh_topDownAttack_basetext {
				idc = -1;
				text = "";
				sizeEx = 0.04;
				w = "SafeZoneW * 0.3";
				x = "SafeZoneX + SafeZoneW * 0.43";
				y = "SafeZoneY + SafeZoneH * 0.68";
			};
		};
	};
	
	class mdh_topDownAttack_rsc_top : mdh_topDownAttack_rsc_base {
		idd = -1;
		name = "mdh_topDownAttack_rsc_top";
		
		class controls {
			class top : mdh_topDownAttack_basepic {
				idc = -1;
				style = 48;
				text = "\A3\ui_f\data\igui\rscingameui\rscoptics_titan\top_co.paa";
				colorText[] = {0.2941, 0.8745, 0.2157, 1.0};
			};
		};
	};
	
	class mdh_topDownAttack_rsc_dir : mdh_topDownAttack_rsc_base {
		idd = -1;
		name = "mdh_topDownAttack_rsc_dir";
		
		class controls {
			class dir : mdh_topDownAttack_basepic {
				idc = -1;
				style = 48;
				text = "\A3\ui_f\data\igui\rscingameui\rscoptics_titan\dir_co.paa";
				y = "SafeZoneY + SafeZoneH * 0.436";
			};
		};
	};
	
	class mdh_topDownAttack_rsc_seek : mdh_topDownAttack_rsc_base {
		idd = -1;
		name = "mdh_topDownAttack_rsc_seek";
		
		class controls {
			class seek : mdh_topDownAttack_basepic {
				idc = -1;
				style = 48;
				text = "\A3\ui_f\data\igui\rscingameui\rscoptics_titan\seek_co.paa";
				colorText[] = {0.2941, 0.8745, 0.2157, 1.0};
				x = "SafeZoneX + SafeZoneW * (switch (format ['%1',(getResolution select 4)]) do {case '1.77778': {0.704}; case '1.33333': {0.773}; case '1.25': {0.790}; case '2.37037': {0.653}; case '4': {0.770}; case '5.33333': {0.703}; default {0.727}})";
				y = "SafeZoneY + SafeZoneH * 0.031";
			};
		};
	};
	
	class mdh_topDownAttack_rsc_missile : mdh_topDownAttack_rsc_base {
		idd = -1;
		name = "mdh_topDownAttack_rsc_missile";
		
		class controls {
			class missile : mdh_topDownAttack_basepic {
				idc = -1;
				style = 48;
				text = "\A3\ui_f\data\igui\rscingameui\rscoptics_titan\missle_co.paa";
				colorText[] = {0.9255, 0.5216, 0.1216, 1.0};
				x = "SafeZoneX + SafeZoneW * (switch (format ['%1',(getResolution select 4)]) do {case '1.77778': {0.144}; case '1.33333': {0.025}; case '1.25': {-0.007}; case '2.37037': {0.233}; case '4': {0.026}; case '5.33333': {0.145}; default {0.104}})";
			};
		};
	};
};
